### ISSUE TITLE
Kéo position

### ISSUE THREAD

**Issue by Cawalunda** [richardbeare/ipa_illustrations#1]
Dear Editors,

just to inform that the marker for Kéo in IPA Illustrations is set in south central Java, and not in south central Flores, where it should be. Flores is located east of Sumbawa. (Flores and Java are similar in shape).

Best wishes

Stefan D

**Comment by richardbeare** [comment]
Thanks for the report. I've updated the location, but please confirm it is OK. If not, please send a google maps query that provides the location you prefer. The current location is given by "Flores, Indonesia"
