### ISSUE TITLE
Language inclusion

### ISSUE THREAD

**Issue by Olanrewajusamuel** [richardbeare/ipa_illustrations#4]
I want to know why Yoruba Language is missing while its counterparts like Hausa and Igbo are present. They are spoken in Nigeria, particularly Yoruba language is spoken in South West Yoruba. I am a native speaker, too. I will appreciate your response.
Thank you.
Olanrewaju.

**Comment by richardbeare** [comment]
Dear Olanrewaju,
Thank you for your interest in the map. The languages marked on the map are those for which a specific type of article has been published. We audited these articles when created the site and continue to add new ones when they are published. The types of article that we map are _Illustrations_  in the _Journal of the International Phonetic Association_ and the _Handbook of the International Phonetic Association_. We are not aware of an illustration of Yoruba in either of these forms - please send us a link if you have found one that we missed.

The map is intended to provide a useful summary of languages for which a certain type of linguistic research has been done. It isn't a complete list of spoken languages.

I hope this helps.
